/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form.Trip;

import Form.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Communication.Communication;
import Domain.Agency;
import Domain.Student;
import Domain.Teacher;
import Domain.Trip;
import Domain.TripStudent;
import Domain.TripTeacher;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SoniXx
 */
public class FrmChangeTrip extends javax.swing.JFrame {

    Trip tripToChange;
    List<Teacher> teacherList;
    List<Student> studentList;
    List<Agency> agencyList;
    
    /**
     * Creates new form FrmAddTrip
     * @param trip
     */
    public FrmChangeTrip(Trip trip) {
        tripToChange = trip;
        teacherList = trip.getTripTeachers();
        studentList = trip.getTripStudents();
        initComponents();
        initAgencyData();
        fillInData();
        disableFields();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initializeForms();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        destinationField = new javax.swing.JTextField();
        startDateField = new javax.swing.JTextField();
        endDateField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        agencyField = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        changeTeacherButton = new javax.swing.JButton();
        changeStudentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Destinacija:");

        jLabel2.setText("Datum pocetka:");

        jLabel3.setText("Datum kraja:");

        jLabel4.setText("Cena:");

        teacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Ime", "Prezime"
            }
        ));
        jScrollPane1.setViewportView(teacherTable);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Prezime", "Razred"
            }
        ));
        jScrollPane2.setViewportView(studentTable);

        saveButton.setText("Zapamti izlet");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Omogući izmene");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        agencyField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        jLabel6.setText("Agencija:");

        changeTeacherButton.setText("Izmeni nastavnike");
        changeTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTeacherButtonActionPerformed(evt);
            }
        });

        changeStudentButton.setText("Izmeni učenike");
        changeStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(destinationField)
                            .addComponent(endDateField)
                            .addComponent(priceField)
                            .addComponent(agencyField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeTeacherButton)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeStudentButton)
                        .addGap(122, 122, 122))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeTeacherButton)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(destinationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(saveButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeStudentButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        gatherAndSetTripData();
        try {
            Communication.getInstance().editTrip(tripToChange);
        } catch (Exception ex) {
            Logger.getLogger(FrmAddTrip.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Sistem je zapamtio izlet.");
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        enableFields();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void changeTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeTeacherButtonActionPerformed
        (new FrmAddTripTeacher(this,teacherList)).setVisible(true);
    }//GEN-LAST:event_changeTeacherButtonActionPerformed

    private void changeStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeStudentButtonActionPerformed
        (new FrmAddTripStudent(this,studentList)).setVisible(true);
    }//GEN-LAST:event_changeStudentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAddTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAddTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAddTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAddTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAddTrip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agencyField;
    private javax.swing.JButton changeStudentButton;
    private javax.swing.JButton changeTeacherButton;
    private javax.swing.JTextField destinationField;
    private javax.swing.JTextField endDateField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField startDateField;
    private javax.swing.JTable studentTable;
    private javax.swing.JTable teacherTable;
    // End of variables declaration//GEN-END:variables
   
    private void gatherAndSetTripData(){
        //Gathering Data
        
        Date startDate = null;
        Date endDate = null;
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            startDate = dateFormat.parse(startDateField.getText());
            endDate = dateFormat.parse(endDateField.getText());
        } catch (ParseException ex) {
            Logger.getLogger(FrmAddTrip.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Setting values of trip fields
        
        tripToChange.setDestination(destinationField.getText());
        tripToChange.setStartDate(startDate);
        tripToChange.setEndDate(endDate);
        tripToChange.setPrice(Long.valueOf(priceField.getText()));
        tripToChange.setAgency(agencyList.get(agencyField.getSelectedIndex()));
        tripToChange.setStudentList(studentList);
        tripToChange.setTeacherList(teacherList);
    }

    private void initializeForms() {
//        tripTeacherForm = new FrmAddTripTeacher(this);
//        tripStudentForm = new FrmAddTripStudent(this);
    }

    void saveTeachers(List<Teacher> selectedTeachers) {
        teacherList = selectedTeachers;
        DefaultTableModel dtm = (DefaultTableModel) teacherTable.getModel();
        clearTable(dtm);
        for(Teacher teacher:teacherList){
            dtm.addRow(new Object[]{teacher.getFirstName(),teacher.getLastName()});
        }
    }

    void saveStudents(List<Student> selectedStudents) {
        studentList = selectedStudents;
        DefaultTableModel dtm = (DefaultTableModel) studentTable.getModel();
        clearTable(dtm);
        for(Student student:studentList){
            dtm.addRow(new Object[]{student.getFirstName(),student.getLastName()});
        }
    }
    
    private void clearTable(DefaultTableModel table){
        int tableRowCount = table.getRowCount();
        for(int i = 0;i<tableRowCount;i++){
            table.removeRow(0);
        }
    }

    private void initAgencyData() {
        try {
            agencyList = Communication.getInstance().getAllAgencies();
            for(Agency school:agencyList){
                agencyField.addItem(school.getName());
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmAddTrip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fillInData() {
        destinationField.setText(tripToChange.getDestination());
        startDateField.setText(tripToChange.getStartDateString());
        endDateField.setText(tripToChange.getEndDateString());
        priceField.setText(tripToChange.getPrice().toString());
        agencyField.setSelectedItem(tripToChange.getAgency().getName());
        fillTeacherTable();
        fillStudentTable();
    }

    private void disableFields() {
        destinationField.setEditable(false);
        startDateField.setEditable(false);
        endDateField.setEditable(false);
        priceField.setEditable(false);
        agencyField.setEnabled(false);
    }

    private void enableFields() {
        destinationField.setEditable(true);
        startDateField.setEditable(true);
        endDateField.setEditable(true);
        priceField.setEditable(true);
        agencyField.setEnabled(true);
    }

    private void fillTeacherTable() {
        DefaultTableModel dtm = (DefaultTableModel) teacherTable.getModel();
        cleanTable(dtm);
        for(Teacher teacher:teacherList){
            dtm.addRow(new Object[]{teacher.getFirstName(),teacher.getLastName()});
        }
    }

    private void fillStudentTable() {
        DefaultTableModel dtm = (DefaultTableModel) studentTable.getModel();
        cleanTable(dtm);
        for(Student student:studentList){
            dtm.addRow(new Object[]{student.getFirstName(),student.getLastName()});
        }
    }
    
    private void cleanTable(DefaultTableModel dtm) {
        int count = dtm.getRowCount();
        for(int i=0;i<count;i++){
            dtm.removeRow(0);
        }
    }
}
